### PR TITLE
Add automated tests for Django 1.11 and supported Python versions.

### PR DESCRIPTION
**Pull request by mgrdcm**

### CODE REVIEW

**Comment by dbrgn** [comment]
Travis might fail, since they have removed older Python compilers in the past, so if that happens I might just as well move the entire CI to CircleCI and ditch Tox...

**Comment by mgrdcm** [comment]
@dbrgn Or just remove tests for Python 2.6/3.3 that are EOL'd?

**Comment by mgrdcm** [comment]
Oh, hah.  They removed even more than that!

**Comment by dbrgn** [comment]
Thanks for the PR, I'm closing this in favor of #22.

**Pull request closed without merging**
